services:
  - type: web
    name: innovartus-saas-app
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true